# TabPre 配置文件
# 配置文件版本，请勿修改
version: 1

# 玩家前缀配置
# 格式: 玩家名: "前缀"
# 支持颜色代码 (&)
prefixes:
  example_player: "&c[VIP]&r "
  another_player: "&6[MVP]&r "

# 消息配置
messages:
  reload-success: "&a配置已重新加载！"
  no-permission: "&c你没有权限执行此命令！"
  help-message: |
    &6=== TabPre 帮助 ===
    &f/tabprefix reload - 重新加载配置
    &f/tabprefix help - 显示此帮助信息 