name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
        with:
          line-endings: auto
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
      
      - name: Fix gradlew permissions
        run: |
          git update-index --chmod=+x gradlew
          chmod +x gradlew
      
      - name: Build Velocity plugin
        run: ./gradlew velocity:build --no-daemon
      
      - name: Build Fabric mod
        run: ./gradlew fabric:build --no-daemon
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: |
            velocity/build/libs/
            fabric/build/libs/
          retention-days: 30