name: Build
on: 
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
          cache: 'gradle'
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
      
      - name: Install dos2unix
        run: sudo apt-get install -y dos2unix
      
      - name: Fix gradlew permissions
        run: |
          dos2unix gradlew
          chmod +x gradlew
      
      - name: Build Velocity plugin
        run: ./gradlew velocity:build --no-daemon --parallel
      
      - name: Build Fabric mod
        run: ./gradlew fabric:build --no-daemon --parallel
      
      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: |
            velocity/build/libs/
            fabric/build/libs/
          retention-days: 30